-- MySQL Script generated by MySQL Workbench
-- Tue Oct 26 19:41:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema Warehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Warehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Warehouse` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `Warehouse` ;

-- -----------------------------------------------------
-- Table `Warehouse`.`Sub_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Sub_role` (
  `Subrole_id` INT UNSIGNED NOT NULL,
  `Subrole_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Subrole_id`),
  UNIQUE INDEX `Subrole_id_UNIQUE` (`Subrole_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Role` (
  `role_id` INT UNSIGNED NOT NULL,
  `subrole_id` INT UNSIGNED NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC),
  INDEX `fk_sub_role_id_idx` (`subrole_id` ASC),
  CONSTRAINT `fkSubRoleId`
    FOREIGN KEY (`subrole_id`)
    REFERENCES `Warehouse`.`Sub_role` (`Subrole_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`User` (
  `User_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  `created_date` TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00",
  `updated_date` TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00",
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `User_id_UNIQUE` (`User_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_role_id_idx` (`role_id` ASC),
  CONSTRAINT `fkUserRoleId`
    FOREIGN KEY (`role_id`)
    REFERENCES `Warehouse`.`Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`City` (
  `City_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`City_id`),
  UNIQUE INDEX `City_id_UNIQUE` (`City_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Climate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Climate` (
  `Climate_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Climate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Climate_id`),
  UNIQUE INDEX `Climate_id_UNIQUE` (`Climate_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Product_type` (
  `Product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Product_id`),
  UNIQUE INDEX `Product_id_UNIQUE` (`Product_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Formular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Formular` (
  `Formular_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Renter_id` INT NOT NULL,
  `Period_begin` TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00",
  `Period_end` TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00",
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`Formular_id`),
  UNIQUE INDEX `Formular_id_UNIQUE` (`Formular_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Rental_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Rental_history` (
  `History_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Formular_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`History_id`),
  UNIQUE INDEX `History_id_UNIQUE` (`History_id` ASC),
  INDEX `fk_formular_id_idx` (`Formular_id` ASC),
  CONSTRAINT `fkRentalFormularId`
    FOREIGN KEY (`Formular_id`)
    REFERENCES `Warehouse`.`Formular` (`Formular_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Storage_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Storage_room` (
  `Storage_room_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Size` DOUBLE NOT NULL,
  `Climate_id` INT UNSIGNED NOT NULL,
  `Product_id` INT UNSIGNED NOT NULL,
  `History_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Storage_room_id`),
  UNIQUE INDEX `Storage_room_id_UNIQUE` (`Storage_room_id` ASC),
  INDEX `fk_climate_id_idx` (`Climate_id` ASC),
  INDEX `fk_product_id_idx` (`Product_id` ASC),
  INDEX `fk_history_id_idx` (`History_id` ASC),
  CONSTRAINT `fkStorageClimateId`
    FOREIGN KEY (`Climate_id`)
    REFERENCES `Warehouse`.`Climate` (`Climate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkStorageProductId`
    FOREIGN KEY (`Product_id`)
    REFERENCES `Warehouse`.`Product_type` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkStorageHistoryId`
    FOREIGN KEY (`History_id`)
    REFERENCES `Warehouse`.`Rental_history` (`History_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Warehouse_has_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Warehouse_has_rooms` (
  `WarehouseHasRooms_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Warehouse_id` INT UNSIGNED NOT NULL,
  `Room_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`WarehouseHasRooms_id`),
  UNIQUE INDEX `WarehouseHasRooms_id_UNIQUE` (`WarehouseHasRooms_id` ASC),
  INDEX `fk_warehouse_id_idx` (`Warehouse_id` ASC),
  INDEX `fk_rooms_id_idx` (`Room_id` ASC),
  CONSTRAINT `fkWarehouseHasRoomsWarehouseId`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `Warehouse`.`Warehouse` (`Warehouse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkWarehouseHasRoomsRoomsId`
    FOREIGN KEY (`Room_id`)
    REFERENCES `Warehouse`.`Storage_room` (`Storage_room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Agents_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Agents_list` (
  `AgentsList_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Agent_id` INT UNSIGNED NOT NULL,
  `Warehouse_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`AgentsList_id`),
  UNIQUE INDEX `Agent/s_id_UNIQUE` (`AgentsList_id` ASC),
  INDEX `fk_role_id_idx` (`Agent_id` ASC),
  INDEX `fk_warehouse_Id_idx` (`Warehouse_id` ASC),
  CONSTRAINT `fkAgentsListRoleId`
    FOREIGN KEY (`Agent_id`)
    REFERENCES `Warehouse`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkAgentsListWarehouseId`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `Warehouse`.`Warehouse` (`Warehouse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Warehouse` (
  `Warehouse_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `warehouse_name` VARCHAR(45) NOT NULL,
  `city_id` INT UNSIGNED NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Number_of_storage_rooms` INT UNSIGNED NOT NULL,
  `rooms_id` INT UNSIGNED NOT NULL,
  `maintanence_id` INT UNSIGNED NOT NULL,
  `Agent/s_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Warehouse_id`),
  UNIQUE INDEX `Warehouse_id_UNIQUE` (`Warehouse_id` ASC),
  INDEX `fk_city_id_idx` (`city_id` ASC),
  INDEX `fk_rooms_id_idx` (`rooms_id` ASC),
  INDEX `fk_agentsList_id_idx` (`Agent/s_id` ASC),
  CONSTRAINT `fkWarehouseCityId`
    FOREIGN KEY (`city_id`)
    REFERENCES `Warehouse`.`City` (`City_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkWarehouseRoomsId`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `Warehouse`.`Warehouse_has_rooms` (`WarehouseHasRooms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkAgentsListId`
    FOREIGN KEY (`Agent/s_id`)
    REFERENCES `Warehouse`.`Agents_list` (`AgentsList_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouse`.`Renter_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Warehouse`.`Renter_information` (
  `Renter_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(15) NOT NULL,
  `City_id` INT UNSIGNED NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Renter_id`),
  UNIQUE INDEX `Renter_id_UNIQUE` (`Renter_id` ASC),
  INDEX `fk_city_id_idx` (`City_id` ASC),
  CONSTRAINT `fkRenterCityId`
    FOREIGN KEY (`City_id`)
    REFERENCES `Warehouse`.`City` (`City_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
